name: Ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    name: Run build, test and lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0'

      - name: Add GitHub NuGet Registry
        run: dotnet nuget add source --username "${{ github.actor }}" --password "%GITHUB_TOKEN%" --store-password-in-clear-text --name github "https://nuget.pkg.github.com/GeoWerkstatt/index.json"

      # Run the npm ci command before building
      # the dotnet project, because the project
      # itself calls npm install if the node_modules
      # folder does not exist.
      - name: Run frontend ci
        working-directory: ./src/Ilicop.Web/ClientApp
        run: npm ci

      - name: Install dependencies
        run: dotnet restore Ilicop.sln
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dotnet
        run: dotnet build Ilicop.sln -c Release --no-restore

      - name: Test
        run: dotnet test Ilicop.sln

      - name: Build frontend
        working-directory: ./src/Ilicop.Web/ClientApp
        run: npm run build --if-present

      - name: Lint frontend
        working-directory: ./src/Ilicop.Web/ClientApp
        run: npm run lint

      - name: Test frontend
        working-directory: ./src/Ilicop.Web/ClientApp
        run: npm run test
